spring:
  application:
    name: Spring Boot Kotlin Demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/testdb
    username: root
    password: 123456
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
  data:
    jdbc:
      dialect: h2
server:
  servlet:
    context-path: /api
